CREATE DATABASE projeto1;

USE projeto1;


CREATE TABLE sebo_usuarios (
    USR_ID INT AUTO_INCREMENT PRIMARY KEY,
    USR_NOME VARCHAR(60) NOT NULL,
    USR_EMAIL VARCHAR(45) NOT NULL,
    USR_SENHA DATE NOT NULL,
    USR_FOTO LONGBLOB,
    USR_TELEFONE VARCHAR(45) NOT NULL,
);
